In [1]:
import pandas as pd
import numpy as np

#Construye visualizaciones base
import matplotlib.pyplot as mpt

#Visualizar estadisticas de alto nivel
import seaborn as sns

#Herramienta de escalado estandar 
from sklearn.preprocessing import StandardScaler

print("OK")

OK

In [14]:
df_crudo=pd.read_csv("ventas_techventas.csv",
    encoding="latin1",
    parse_dates=["fecha"])
df_crudo.head()

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2.0,1200.0,0.10,Ana Lï¿½ï¿
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15.0,25.0,0.00,Carlos Ruiz
2,"1003,2024-01-10,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10.0,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3.0,1200.0,0.15,Carlos Ruiz

# Primeros datos "Incorrectos": 
-order_id-cliente_id- Cantidad Cambiar a INT
-Fecha, debe ser en dataTime
-11 nulos en cada categoria

In [7]:
df_crudo.info()
df_crudo.describe().round(0)

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         60 non-null     str
 1   fecha            49 non-null     str
 2   cliente_id       49 non-null     str
 3   cliente_nombre   49 non-null     str
 4   region           49 non-null     str
 5   producto         48 non-null     str
 6   categoria        49 non-null     str
 7   cantidad         49 non-null     float64
 8   precio_unitario  49 non-null     float64
 9   descuento        49 non-null     float64
 10  vendedor         49 non-null     str
dtypes: float64(3), str(8)
memory usage: 5.3 KB

       cantidad  precio_unitario  descuento
count      49.0             49.0       49.0
mean       11.0            385.0        0.0
std         9.0            497.0        0.0
min        -1.0             25.0        0.0
25%         3.0             85.0        0.0
50%         8.0             95.0        0.0
75%        18.0           1200.0        0.0
max        35.0           1200.0        0.0

In [11]:
nulosTotales= df_crudo.isnull().sum()
nulosTotales

order_id            0
fecha              11
cliente_id         11
cliente_nombre     11
region             11
producto           12
categoria          11
cantidad           11
precio_unitario    11
descuento          11
vendedor           11
dtype: int64

In [12]:
duplicadosTotales=df_crudo.duplicated().sum()
duplicadosTotales

np.int64(0)